POST http://localhost:3001/api/register
Content-Type: application/json

{
    "admin": false,
    "nombre": "Samuel",
    "apellido": "Angulo",
    "correo": "samuelricardo@gmail.com",
    "password": "123456",
    "rut": "26022413-1",
    "grupoSanguineo": "O+",
    "telefono": "123456789",
    "fechaNacimiento": "2001-05-09"
}